# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Mern-post   # 👈 Your self-hosted agent pool

steps:
# Install root dependencies (if package.json exists at root)
- task: Npm@1
  inputs:
    command: 'install'

# Install server dependencies
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'server'

# Install client dependencies
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'client'

# Build client
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'client'
    customCommand: 'run build'

# Copy built client + server to staging
- task: CopyFiles@2
  inputs:
    Contents: |
      client/dist/**   # if React CRA → use build/**
      server/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish build artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'