# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Mern-post   

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: "Install Node.js"

# Install server dependencies
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'server'

# Install client dependencies
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'client'

# Build client
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'client'
    customCommand: 'run build'

# Copy built client + server to staging
- task: CopyFiles@2
  inputs:
    Contents: |
      client/dist/**   # if CRA → change to client/build/**
      server/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish build artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'